db = db.getSiblingDB("cards");
db.createCollection('cards');
db.cards.insertMany([
    {
        'card_id':'1',
        'image_name':'angular.png',
        'score':10
    },
    {
        'card_id':'2',
        'image_name':'react.png',
        'score':10
    },
    {
        'card_id':'3',
        'image_name':'logo.png',
        'score':10
    },
    {
        'card_id':'4',
        'image_name':'svelte.png',
        'score':10
    }
    ]);